baseURL = "/"
languageCode = "id-id"
title = "sinauRien"
theme = "jawa"
summaryLength = 10
paginate = 6
[author]
    name = "M Faruq Syarifudin"
    homepage = "https://web.facebook.com/profile.php?id=100009944859170"
    bio = "Game for fun"
    image = "/assets/img/download.jfif"

[params]
    Description = "Tanpa niat belajar tidak akan dimulai"
[taxonomies]
    category = "categories"
    tag = "tags"
    topik = "topik"
    bahasa = "bahasa"

