baseURL = "https://sinaudhisik.netlify.app/"
languageCode = "id-id"
title = "sinaudhisik"
theme = "jawa"
summaryLength = 8
paginate = 6
[author]
    name = "M Faruq Syarifudin"
    homepage = "https://web.facebook.com/profile.php?id=100009944859170"
    bio = "Game for fun"
    image = "/assets/img/download.jfif"

[params]
    Description = "Tanpa niat belajar tidak akan dimulai"
[taxonomies]
    category = "categories"
    tag = "tags"
    topik = "topik"
    bahasa = "bahasa"

# [markup]
# taskLists = false

[params]
responsiveImages = false # The default is true so you only need this if you want to turn off responsive images
linkFullImages = true # The default is false. This enables wrapping responsive images in a link the original image
convertImagesTo = "webp" # Default is not set (no conversion). Convert all assets and page bundle images to some format (in the example, 'webp').
# Note that when using this that the linkFullImages above will link the full size, but converted, image.